import type { RoleDef, RoleId } from "./types";

export const ROLES: Record<RoleId, RoleDef> = {
  mafia: {
    id: "mafia",
    name: "Mafia",
    faction: "mafia",
    tagline: "The hidden hand",
    description: "You hunt under the cover of night. Trust no outsider.",
    ability: "Each night, conspire with your family to kill one villager.",
    emoji: "🩸",
  },
  barman: {
    id: "barman",
    name: "Barman",
    faction: "mafia",
    tagline: "Pours poison and lies",
    description: "A poisoned drink silences the gifted.",
    ability: "Each night, block one player from using their ability.",
    emoji: "🥃",
  },
  detective: {
    id: "detective",
    name: "Detective",
    faction: "town",
    tagline: "Seeker of truth",
    description: "Cigarette smoke, a notepad, and a sharp instinct.",
    ability: "Each night, investigate one player to learn if they are Mafia.",
    emoji: "🔍",
  },
  doctor: {
    id: "doctor",
    name: "Doctor",
    faction: "town",
    tagline: "Keeper of breath",
    description: "Hands steady, even when the bullets fly.",
    ability: "Each night, save one player from death.",
    emoji: "⚕️",
  },
  guard: {
    id: "guard",
    name: "Guard",
    faction: "town",
    tagline: "Iron between sins",
    description: "Stands watch at the chosen door until dawn.",
    ability: "Each night, protect one player from attacks.",
    emoji: "🛡️",
  },
  vigilante: {
    id: "vigilante",
    name: "Vigilante",
    faction: "town",
    tagline: "Justice off the books",
    description: "When the law sleeps, the gun speaks.",
    ability: "Each night, you may shoot one player you suspect of being Mafia.",
    emoji: "🔫",
  },
  villager: {
    id: "villager",
    name: "Villager",
    faction: "town",
    tagline: "Ordinary, until tested",
    description: "No gift, no badge — only your voice in the daylight.",
    ability: "Argue, accuse, vote. Survive the night.",
    emoji: "🕯️",
  },
};
